### ISSUE TITLE
Kuupäevade salvestamine kellaajata

### ISSUE THREAD

**Issue by mitselek** [entu/webapp#73]
![image](https://github.com/user-attachments/assets/fe3a5fa4-1576-4c7c-9b85-8302da630dde)
praegu salvestatakse koos vööndiajaga, ehk kuupäev saab vastavalt vaataja asukohale veits nihkuda

``` yaml
  children:
    - label: Otsuse kuupäev
      labelPlural: Otsuse kuupäevad
      mandatory: true
      name: otsuse_kp
      ordinal: 4
      public: true
      type: date
      values:
        - _id: 66daae4bf2daf46b3145607e
          date: 1925-02-17T22:00:00.000Z
```
